package tchatjava;

import java.awt.event.KeyEvent;
import java.util.*;
import message.MotCle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ponsma
 */
public class TchatCreationCompte extends javax.swing.JFrame {

    private String pseudo;
    private ArrayList<String> psds;
    private Compte compt;

    /**
     * Creates new form TchatCreationCompte
     */
    public TchatCreationCompte() {
        compt = new Compte();
        psds = compt.getSave().getPseudos();
        initComponents();
    }
    
    private void connexion() {
        Integer port = Integer.parseInt(jTextFieldPort.getText());
        String host = jTextFieldHost.getText();

        if (port != null && !host.isEmpty()) {
            compt.connexionServeur(port, host);
            boolean pris = false;
            if (!((String) jComboBoxPseudo.getSelectedItem()).isEmpty()) {
                pseudo = (String) jComboBoxPseudo.getSelectedItem();
                if (compt.getSave().getPseudos().contains(pseudo)) {
                    compt.getSave().getPseudos().remove(pseudo);
                } else {
                    pris = compt.ConnectionVerifPseudo(pseudo);
                }
                if (!pris) {
                    compt.getSave().setPseudo(pseudo);
                    compt.getSave().sauve();
                    this.dispose();
                    TchatCreationServeur tcs = new TchatCreationServeur(this, false, compt);
                    tcs.setVisible(true);
                } else {
                    MessageErreur msserror = new MessageErreur();
                    msserror.setText("le pseudo a déja été pris");
                    msserror.setVisible(true);
                }
            } else {
                MessageErreur d = new MessageErreur();
                d.setText("Vous devez mettre un pseudo.");
                d.setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConnexion = new javax.swing.JButton();
        jComboBoxPseudo = new javax.swing.JComboBox();
        jButtonQuitter = new javax.swing.JButton();
        jTextFieldPort = new javax.swing.JTextField();
        jTextFieldHost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConnexion.setText("Connexion");
        jButtonConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnexionActionPerformed(evt);
            }
        });

        jComboBoxPseudo.setEditable(true);
        jComboBoxPseudo.setModel(new javax.swing.DefaultComboBoxModel(psds.toArray()));

        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });

        jTextFieldPort.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPort.setText("51569");
        jTextFieldPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPortKeyPressed(evt);
            }
        });

        jTextFieldHost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldHost.setText("localhost");
        jTextFieldHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldHostKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonQuitter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jButtonConnexion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldHost)
                            .addComponent(jTextFieldPort)
                            .addComponent(jComboBoxPseudo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jComboBoxPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConnexion)
                    .addComponent(jButtonQuitter))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnexionActionPerformed
        // TODO add your handling code here:
        this.connexion();
    }//GEN-LAST:event_jButtonConnexionActionPerformed

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
        if (compt.getOuvert()) {
            compt.ecrire(pseudo, "", MotCle.CLOSE, "");
            compt.fermerSocket();
        }
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    private void jTextFieldPortKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPortKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.connexion();
        }
    }//GEN-LAST:event_jTextFieldPortKeyPressed

    private void jTextFieldHostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHostKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.connexion();
        }
    }//GEN-LAST:event_jTextFieldHostKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TchatCreationCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TchatCreationCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TchatCreationCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TchatCreationCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TchatCreationCompte().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnexion;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JComboBox jComboBoxPseudo;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables
}
